apiVersion: example.com.my.domain/v1beta1
kind: VisitorsApp
metadata:
  name: visitorsapp-sample
  namespace: visitors-operator-system
spec:
  backendSize: 1
  backendAutoScaling: true
  backendServiceNodePort: 30685
  frontendTitle: "visitors app"
  frontendSize: 1
  frontendAutoScaling: true
  frontendServiceNodePort: 30686
