apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  # root password is required to be specified
  ROOT_PASSWORD: cGFzc3dvcmQ=
  ## application credentials that will be created at cluster bootstrap
  DATABASE: dmlzaXRvcnNfZGI=
  USER: dmlzaXRvcnMtdXNlcg==
  PASSWORD: dmlzaXRvcnMtcGFzcw==
