apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: default
spec:
  rules:
  - host: visitorsbackend.com
    http:
      paths:
      - backend:
          serviceName: visitorsapp-sample-backend-service
          servicePort: 8000
